spring:

  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: validate
  datasource:
    username: 'sa'
    url: jdbc:h2:mem:testdb
    password: ''
  h2:
    console:
      enabled: 'true'
server:
  port: 8080

